export interface ICar {
	c_No: number;
	stnd_C_Nm: string;
}

export interface ICarBooking {
	booking_ID: string;
	cfm_yn: boolean;
	cfm_date: null;
	hr_cfm_yn: boolean;
	guid: string;
	booking_date: Date;
	start_date: Date;
	end_date: Date;
	meet_date: null;
	start_time: null;
	op_emp_no: string;
	car_id: number;
	st_c: null;
	lst_updt_date: Date;
	sms_yn: null;
	kind: null;
	meet_ID: null;
	branch_ID: null;
	webex: null;
	cnid: string;
	op_emp_nm: string;
	op_emp_email: null;
	optional_emp_no: null;
	optional_nm: null;
	optional_email: null;
	rmks: string;
	st_c_nm: string;
	title: null;
	meet_content: null;
	meet_nm: null;
	meet_mail: null;
	cc: null;
	files: null;
	invite: null;
	ext: null;
	email: string;
	sT_C: string;
	team: string;
	subTeam: string;
	empNm: string;
	destination: string;
	lese_ID: number;
	ls_Nm: string;
}

// {
//   ALIAS_EMP_NM:     string;
//   BOOKINGDATE:      string;
//   BOOKING_DATE:     Date;
//   BOOKING_ID:       string;
//   BOOKING_TP:       string;
//   BOOKING_TP_NM:    string;
//   BRANCH:           string;
//   CARD_ID1:         null;
//   CARD_ID2:         null;
//   CARD_SEQ1:        number;
//   CARD_SEQ2:        number;
//   CAR_ID:           number;
//   CAR_NM:           null;
//   CFM_YN:           boolean;
//   CITY_ID:          string;
//   DESTINATION:      string;
//   DISTANCE:         number;
//   DISTRICT_ID:      string;
//   EMP_EMAIL:        string;
//   END_DATE:         Date;
//   END_KM:           number;
//   Email:            string;
//   EmpNm:            string;
//   FA:               number;
//   FS_EMP_NM:        string;
//   FULL_ADDRESS:     string;
//   GUID:             string;
//   HR_CFM_YN:        boolean;
//   HR_RMKS:          string;
//   LESE_ID:          number;
//   LST_NM:           string;
//   LST_UPDT_DATE:    Date;
//   LS_NM:            string;
//   LS_NM_ALIAS:      string;
//   OPTIONAL_ADDRESS: string;
//   OPTIONAL_EMP_NO:  string;
//   OP_EMP_NM:        string;
//   OP_EMP_NO:        string;
//   OVERNIGHT_YN:     boolean;
//   RDISTANCE:        number;
//   REMIND_YN:        boolean;
//   RMKS:             string;
//   R_END_DATE:       Date;
//   R_START_DATE:     Date;
//   START_DATE:       Date;
//   START_KM:         number;
//   ST_C:             string;
//   ST_C1:            number;
//   SubTeam:          string;
//   TNO1:             null;
//   TOLL_FEE:         number;
//   TOTAL_FEE1:       number;
//   TOTAL_FEE2:       number;
//   Team:             string;
//   WARD_ID:          string;
//   emp_no:           string;
//   sENDDATE:         string;
//   sRENDDATE:        string;
//   sRENDDATE1:       string;
//   sRSTARTDATE:      string;
//   sRSTARTDATE1:     string;
//   sSTARTDATE:       string;
//   sTollFee:         string;
//   st_c_nm:          string;
//   st_c_nm_dtl:      null;
//   st_c_nm_dtl1:     string;
//   stc_nm_dtl2:      string;
// }
