export default interface ICustomer {
	// lese_ID: number;
	// ls_nm: string;
	// addr_v: string;
	// addr: string;
	// ls_nm_v: string;
	// tax_code: string;
	// tno: string;
	// person: null;
	// src: string;
	// city_code: string;
	// email: string;
	// st_c: number;
	// op_emp_nm: string;
	// team_leader: string;
	// flat_long: string;
	// dealer_yn: boolean;
	// customer_type: string;
	// src_nm: string;
	// ob: number;
	// check_leseid: number;
	// contact_person: number;
	// login_App: string;
	// reg_id : string;
	ADDR: string;
	ADDR_V: string;
	CITY_CODE: string;
	EMAIL: string;
	FLAT_LONG: string;
	LESE_ID: number;
	LS_NM: string;
	LS_NM_V: string;
	OP_EMP_NM: string;
	PERSON: string;
	SRC: string;
	ST_C: number;
	TAX_CODE: string;
	REG_ID: string;
	TEAM_LEADER: string;
	TNO: string;
	OB: boolean;
	CHECK_LESEID: number;
	CONTACT_PERSON: number;
	SRC_NM: string;
	LOGIN_APP: string;
}
