export interface IFixedAsset {
	assetCode: string;
	assetname: string;
	assetnamevn: null;
	parentID: string;
	unitID: string;
	manufactureID: null;
	countryID: string;
	companyID: string;
	branchID: string;
	deptpartmentID: null;
	hrmanagerID: string;
	managerID: null;
	employeeID: null;
	managedwarehouseID: string;
	termwarranty: number;
	isfixedasset: boolean;
	isLoadTest: boolean;
	isTesting: boolean;
	isSeparation: boolean;
	isSeparationIssue: boolean;
	depreciationyear: null;
	depreciationtimeyear: null;
	depreciationbyrate: boolean;
	depreciationrate: null;
	accountasset: null;
	accountasset_tw: null;
	accountdepreciation: null;
	accountdepreciation_tw: null;
	isenabled: boolean;
	crtd_user: string;
	crtd_datetime: Date;
	lupd_user: null;
	lupd_datetime: null;
	kind_fixedasset: string;
	kind_separation: string;
	kind_separationissue: string;
	assetcategoryname: string;
	qr_data: string;
	qr_file_url: string;
	qr_file_name: string;
	print_number: string;
}

//{
//     AccountAsset:           null;
//     AccountAsset_TW:        null;
//     AccountDepreciation:    null;
//     AccountDepreciation_TW: null;
//     AssetCategoryName:      string;
//     AssetCode:              string;
//     AssetCode1:             string;
//     AssetName:              string;
//     AssetName_VN:           null;
//     BranchID:               string;
//     CompanyID:              string;
//     CountryID:              null;
//     Crtd_DateTime:          Date;
//     Crtd_User:              string;
//     DepreciationByRate:     null;
//     DepreciationRate:       null;
//     DepreciationTimeYear:   null;
//     DepreciationYear:       null;
//     DeptpartmentID:         string;
//     EmployeeID:             null;
//     HRManagerID:            string;
//     IsEnabled:              boolean;
//     IsFixedAsset:           boolean;
//     IsLoadTest:             boolean;
//     IsSeparation:           boolean;
//     IsSeparationIssue:      boolean;
//     IsTesting:              boolean;
//     Kind_FixedAsset:        string;
//     Kind_Separation:        string;
//     Kind_SeparationIssue:   string;
//     LUpd_DateTime:          Date;
//     LUpd_User:              string;
//     ManagedWarehouseID:     string;
//     ManagerID:              string;
//     ManufactureID:          null;
//     PRINT_NUMBER:           number;
//     ParentID:               string;
//     QR_DATA:                string;
//     QR_FILE_NAME:           string;
//     QR_FILE_URL:            string;
//     TermWarranty:           null;
//     UnitID:                 string;
//     AssetLocation:          string;
//     AssetStatus:            string;
// }
export interface IFixedAssetDetail {
	// AccountAsset: null;
	// AccountAsset_TW: null;
	// AccountDepreciation: null;
	// AccountDepreciation_TW: null;
	// ActualUseDate: null;
	// AmountCost: null;
	// AmountDepreciate: number;
	// AntivirusSoftExpr: null;
	// AntivirusVersion: string;
	// Antivirus_YN: boolean;
	// AppearDate: null;
	// ApporvedDate: null;
	// ApporvedStatus: string;
	// AssetCategoryID: string;
	// AssetCategoryName_NM: string;
	// AssetCode: string;
	// AssetCodeOld: null;
	// AssetLocation: string;
	// AssetName: string;
	// AssetName_VN: string;
	// AssetStatus: string;
	// AssetStatus_NM: string;
	// BarCodeImage: null;
	// BranchID: string;
	// BranchID1: string;
	// BudgetSourceID: null;
	// BuyDate: null;
	// COMPANY_ID: null;
	// C_NO: string;
	// Capacity: null;
	// ColorID: null;
	// CompanyID: string;
	// ComputerName: null;
	// CountryID: null;
	// Crtd_DateTime: Date;
	// Crtd_User: string;
	// DIV_CODE: null;
	// DIV_NM: null;
	// DIV_NM_SHORT: null;
	// DIV_NM_V: null;
	// DepreciationByRate: null;
	// DepreciationMonth: null;
	// DepreciationRate: null;
	// DepreciationTimeYear: null;
	// DepreciationYear: null;
	// DeptpartmentID: string;
	// DeptpartmentID_NM: null;
	// Description: null;
	// DocumentAttach: null;
	// DocumentFilename: null;
	// EMAIL_TEAM: null;
	// EmployeeID: string;
	// EmployeeID_NM: string;
	// Feature: null;
	// FloorNumber: null;
	// HRManagerID: string;
	// HRManagerID_NM: string;
	// IPAddress: null;
	// InvoiceDate: null;
	// InvoiceNumber: null;
	// InvoiceSeries: null;
	// IsColor: boolean;
	// IsEnabled: boolean;
	// IsEndAsset: boolean;
	// IsFixedAsset: boolean;
	// IsLoadTest: boolean;
	// IsSeparation: boolean;
	// IsSeparationIssue: boolean;
	// IsSuspend: boolean;
	// IsSuspendDepreciation: boolean;
	// IsTesting: boolean;
	// Kind_FixedAsset: string;
	// LST_UPDT_DATE: null;
	// LUpd_DateTime: null;
	// LUpd_User: null;
	// LastestAssetCategoryID: null;
	// LevelHouse: null;
	// MACAddress: null;
	// MNGR: null;
	// MaintenanceSchedule: null;
	// ManagedWarehouseID: string;
	// ManagedWarehouseID_NM: string;
	// ManagerDepartMent: string;
	// ManagerID: string;
	// ManagerID_NM: null;
	// ManufactureID: null;
	// Model: string;
	// OP_EMP_NO: null;
	// OfficeKey: null;
	// OfficeVersion: string;
	// Office_Lable_YN: boolean;
	// Office_OEM_YN: boolean;
	// OtherFilename: null;
	// PODate: null;
	// POFilename: null;
	// PONumber: null;
	// POSupplierID: string;
	// ParentID: string;
	// PartNumber: null;
	// ProductCode: null;
	// ProductionYear: null;
	// Quantity: number;
	// QuantityDepreciation: number;
	// Quantity_NM: number;
	// RMKS: null;
	// RecordNumber: null;
	// RemainDepreciation: number;
	// STND_C_NM: string;
	// ST_C: string;
	// ST_C1: null;
	// SerialNumber: string;
	// Specifications: null;
	// SquareConstruction: null;
	// SquareFloor: null;
	// SquareHouse: null;
	// SquareUsing: null;
	// TW_STAFF: null;
	// TeamViewerID: null;
	// TermWarranty: null;
	// TotalDepreciation: number;
	// UltraviewerID: null;
	// UnitID: string;
	// UnitID_NM: string;
	// UserApporved: string;
	// WarrantNumber: null;
	// WarrantyCompany: null;
	// WarrantyFromDate: null;
	// WarrantyPlace: null;
	// WarrantyToDate: null;
	// WindowKey: null;
	// WindowVersion: string;
	// Window_Lable_YN: boolean;
	// Window_OEM_YN: boolean;

	assetCode: string;
	assetname: string;
	assetnamevn: null;
	parentID: string;
	unitID: string;
	manufactureID: string;
	countryID: string;
	companyID: string;
	branchID: string;
	deptpartmentID: string;
	hrmanagerID: string;
	managerID: null;
	employeeID: string;
	managedwarehouseID: string;
	termwarranty: number;
	isfixedasset: boolean;
	isLoadTest: boolean;
	isTesting: boolean;
	isSeparation: boolean;
	isSeparationIssue: boolean;
	depreciationyear: null;
	depreciationtimeyear: null;
	depreciationbyrate: boolean;
	depreciationrate: null;
	accountasset: null;
	accountasset_tw: null;
	accountdepreciation: null;
	accountdepreciation_tw: null;
	isenabled: boolean;
	crtd_user: string;
	crtd_datetime: Date;
	lupd_user: string;
	lupd_datetime: Date;
	kind_fixedasset: string;
	kind_separation: null;
	kind_separationissue: null;
	assetcategoryname: null;
	qr_data: null;
	qr_file_url: null;
	qr_file_name: null;
	print_number: null;
}
