export interface ISeller {
	ACC_NO: string;
	ADDR: string;
	ADDR_BANK: string;
	ADDR_V: string;
	BANK: string;
	BANK_VN: string;
	BRAND_CODE: string;
	CILC_CODE: string;
	COMM_YN: null;
	DATE_LUPD: Date;
	ESBT_DATE: Date;
	FAX: string;
	FunctionName: string;
	GROUP_ID: string;
	IBAN: string;
	ID: number;
	IDBY_PERSON: null;
	IDBY_PERSON_V: null;
	IDDATE_PERSON: null;
	IDNO_PERSON: null;
	ID_DEALER_OLD: number;
	INPUT_DATE: null;
	IS_LOCKED: null;
	LAT_LNG: null;
	LST_UPDT_DATE: Date;
	NAT_C: string;
	OP_EMP_NO: string;
	ORG_TP: null;
	PERSON_NM: string;
	PERSON_NM_V: string;
	PIC: string;
	PRODUCT_CODE: string;
	REG_BY: string;
	REG_BY_EN: string;
	REG_DATE: Date;
	REG_ID: string;
	SELLER_NM: string;
	SELLER_NM_V: string;
	SELLER_TP: string;
	SWIFT_CODE: string;
	TAX_CODE: string;
	TIT: string;
	TNO: string;
	TNO_PERSON: string;
	TypeOfCompany: string;
	USER_LUPD: string;
}

// export interface ISeller {
// 	id: number;
// 	seller_nm: string;
// 	seller_nm_v: string;
// 	addr: string;
// 	addr_v: string;
// 	tax_code: string;
// 	tno: string;
// 	nat_c: string;
// 	person_nm: string;
// 	tit: string;
// 	acc_no: string;
// 	bank: string;
// 	bank_vn: string;
// 	addr_bank: string;
// 	swift_code: string;
// 	fax: string;
// 	seller_tp: string;
// 	reg_id: string;
// 	reg_date: Date;
// 	reg_by: string;
// 	reg_by_en: string;
// 	op_emp_no: string;
// 	lst_updt_date: Date;
// 	org_tp: null;
// 	group_id: string;
// 	idno_person: null;
// 	tno_person: string;
// 	iddate_person: null;
// 	idby_person: null;
// 	idby_person_v: null;
// 	person_nm_v: string;
// 	iban: string;
// 	id_dealer_old: number;
// 	input_date: null;
// 	esbt_date: Date;
// 	brand_code: string;
// 	product_code: string;
// 	comm_yn: boolean;
// 	typeofcompany: string;
// 	lat_lng: string;
// 	cilc_code: string;
// 	user_lupd: string;
// 	functionname: string;
// 	date_lupd: Date;
// 	is_locked: null;
// 	pic: string;
// }
