export interface ITeleHistory {
  CALLCONTENT: string;
  CITY:        string;
  CITY_NM:     string;
  CONTACT_NM:  string;
  CallDate:    string;
  CallDate1:   Date;
  DISTRICT:    string;
  EMP_MAIL:    string;
  EMP_NM:      string;
  EMP_NO:      string;
  GRADE:       string;
  GRADE_NM:    string;
  LESE_ADDR:   string;
  LESE_NAME:   string;
  LESE_TNO:    string;
  LST_NM:      string;
  LS_PUR:      string;
  MAIL_YN:     boolean;
  MANAGER_NO:  string;
  MOBILE:      string;
  RECALLDATE:  null;
  RECALL_DATE: Date;
  SUB_BOSS_NO: string;
  SUB_TEAM:    string;
  TAX_CODE:    string;
  TEAM:        string;
  TELE_ID:     string;
}
