export interface IValidAprv {
	// APNO: string;
	// APRVAMT: string;
	// APRVDATE: string;
	// APRV_DATE: string;
	// CNID: string;
	// COMM_STC: string;
	// COMM_STC_NM?: string;
	// CR_TP_NM: string;
	// ContTime_Act: string;
	// ContTime_Show: number;
	// DSBT_STA: number;
	// FINAMT: string;
	// FS_EMP_NM: string;
	// IRR: number;
	// LS_INT_R: number;
	// LS_NM: string;
	// NPV: number;
	// OP_EMP_NO: string;
	// R_DSBT_AMT: number;
	// SUB_TEAM: string;
	// TEAM: string;
	// cons_CR_TP: string;
	// expDATE: string;
	// exp_date: string;
	// expry_date: 3;

	team: string;
	sub_Team: string;
	cons_CR_TP: string;
	cr_Tp_Nm: string;
	comm_Stc: string;
	comm_Stc_nm: null;
	aprvDate: string;
	expDate: string;
	fs_Emp_NM: string;
	apNo: null;
	cnid: string;
	irr: number;
	ls_Int_R: string;
	ls_nm: string;
	op_Emp_No: string;
	npv: string;
	aprvAmt: number;
	aprv_Date: Date;
	dsbt_Sta: number;
	finAmt: number;
	r_Dsbt_Amt: number;
	expry_date: number;
	exp_date: Date;
	contTime_Show: number;
	contTime_Act: string;
}
