export default interface IVisit_Trading {
	// {
	// 	ADDR: string;
	// 	ADDR_V: string;
	// 	APPROVAL_DATE: string;
	// 	APPROVAL_STATUS: string;
	// 	APPROVAL_USER: string;
	// 	BAS_DATE: string;
	// 	Customer_Type: string;
	// 	EMP_NM: string;
	// 	FAX: string;
	// 	FS_EMP_NM: string;
	// 	GRADE: string;
	// 	INDS_TP: string;
	// 	INT_PER: string;
	// 	INT_TIME: number;
	// 	LESE_ID: number;
	// 	LESE_STC: string;
	// 	LESE_TP: number;
	// 	LESE_TP_NM: string;
	// 	LS_NM: string;
	// 	LS_NM_V: string;
	// 	LS_PUR: string;
	// 	MANAGER_NO: string;
	// 	NXT_MOVE: string;
	// 	OP_EMP_NO: string;
	// 	PERSON_NM: string;
	// 	PHONE_NO: string;
	// 	PIC_DEPT_CODE: string;
	// 	POS: string;
	// 	PUR: string;
	// 	RMKS: string;
	// 	SEQ: number;
	// 	SRC: string;
	// 	STATUS: number;
	// 	SUB_TEAM: string;
	// 	TEAM: string;
	// 	TIT_NM: string;
	// 	TRVL_TIME: number;
	// 	VISIT_DATE: string;
	// 	VISIT_TP: number;
	// 	co_mo_emp_no: string;
	// 	cust_source: string;
	// 	insr_comp: string;
	// 	visit_stt: string;
	// 	Visit_Method: string;
	// 	FLAT_LONG: string;
	// 	VisitAddressID: string;
	// 	AddressType: string;
	// 	VisitAddress: string;
	// 	DISTANCE: number;
	// };

	seq: number;
	lese_ID: number;
	ls_Nm: string;
	ls_Nm_V: string;
	addr: string;
	addr_V: string;
	emp_Nm: string;
	op_Emp_No: string;
	int_per: string;
	int_time: number;
	trvL_TIME: number;
	bas_Date: string;
	visiT_DATE: string;
	fS_EMP_NM: string;
	lesE_TP_NM: string;
	lesE_TP: number;
	pos: string;
	nxT_MOVE: string;
	pur: string;
	rmks: string;
	lS_PUR: string;
	persoN_NM: string;
	tiT_NM: string;
	phonE_NO: string;
	fax: string;
	team: string;
	visiT_TP: number;
	suB_TEAM: string;
	manageR_NO: string;
	indS_TP: string;
	lesE_STC: string;
	src: string;
	grade: string;
	approvaL_STATUS: string;
	approvaL_DATE: string;
	approvaL_USER: string;
	status: number;
	cust_source: string;
	insr_comp: string;
	piC_DEPT_CODE: string;
	visit_stt: string;
	co_mo_emp_no: string;
	visiT_TYPE: string;
	visit_Method: string;
	attached_File: string;
	flaT_LONG: string;
	visiT_METHOD_NM: string;
	addressType: string;
	visitAddress: string;
	visitChecked_YN: string;
	visitAddressID: string;
	customer_Type: string;
	distance: string;
}
