export const GET_LIST_ROOM = 'GET_LIST_ROOM';
export const GET_LIST_ROOM_SUCCESS = 'GET_LIST_ROOM_SUCCESS';
export const GET_LIST_ROOM_FAIL = 'GET_LIST_ROOM_FAIL';

export const GET_LIST_BOOK_MEETING = 'GET_LIST_BOOK_MEETING';
export const GET_LIST_BOOK_MEETING_SUCCESS = 'GET_LIST_BOOK_MEETING_SUCCESS';
export const GET_LIST_BOOK_MEETING_FAIL = 'GET_LIST_BOOK_MEETING_FAIL';
