export const GET_LIST_CAR_BOOKING = 'GET_LIST_CAR_BOOKING';
export const GET_LIST_CAR_BOOKING_SUCCESS = 'GET_LIST_CAR_BOOKING_SUCCESS';
export const GET_LIST_CAR_BOOKING_FAIL = 'GET_LIST_CAR_BOOKING_FAIL';
