export const GET_LIST_CONSULTATION = 'GET_LIST_CONSULTATION';
export const GET_LIST_CONSULTATION_SUCCESS = 'GET_LIST_CONSULTATION_SUCCESS';
export const GET_LIST_CONSULTATION_FAIL = 'GET_LIST_CONSULTATION_FAIL';



export const SET_SELECTED_CITY = 'SET_SELECTED_CITY';
export const SET_CUSTOMER_NAME = 'SET_CUSTOMER_NAME';
export const SET_PROGRAM = 'SET_PROGRAM';
export const SET_KIND_VEHICLE = 'SET_KIND_VEHICLE';
export const SET_KIND_CREDIT_TYPE = 'SET_KIND_CREDIT_TYPE';
export const SET_KIND_UNDER_COMMISSION = 'SET_KIND_UNDER_COMMISSION';
export const SET_KIND_CREDIT_VISIT_DATE = 'SET_KIND_CREDIT_VISIT_DATE';
export const SET_VISIT_DATE = 'SET_VISIT_DATE';
export const SET_CUSTOMER_RESOURCE = 'SET_CUSTOMER_RESOURCE';
export const SET_DEALER_NAME = 'SET_DEALER_NAME';
export const SET_KIND_FUNDING_PURPOSE = 'SET_KIND_FUNDING_PURPOSE';
// export const SET_FUNDING_PURPOSE = 'SET_FUNDING_PURPOSE';

export const SET_LEASED_ASSETS = 'SET_LEASED_ASSETS';
export const SET_OTHER_CONDITIONS = 'SET_OTHER_CONDITIONS';
export const SET_OPINIONS_OF_SALES_DEPT = 'SET_OPINIONS_OF_SALES_DEPT';


export const SET_LIST_VALUE_CREDIT_PROGRESS = 'SET_LIST_VALUE_CREDIT_PROGRESS';

