export const GET_LIST_CONTRACT = 'GET_LIST_CONTRACT';
export const GET_LIST_CONTRACT_SUCCESS = 'GET_LIST_CONTRACT_SUCCESS';
export const GET_LIST_CONTRACT_FAIL = 'GET_LIST_CONTRACT_FAIL';

export const SET_LIST_DEPT_AMOUNT_VND = 'SET_LIST_DEPT_AMOUNT_VND';
export const RESET_LIST_DEPT_AMOUNT_VND = 'RESET_LIST_DEPT_AMOUNT_VND';
export const SET_LIST_DEPT_AMOUNT_USD = 'SET_LIST_DEPT_AMOUNT_USD';
export const RESET_LIST_DEPT_AMOUNT_USD = 'RESET_LIST_DEPT_AMOUNT_USD';

