export const GET_LIST_CONTRACT_TIMELINE = 'GET_LIST_CONTRACT_TIMELINE';
export const GET_LIST_CONTRACT_TIMELINE_SUCCESS = 'GET_LIST_CONTRACT_TIMELINE_SUCCESS';
export const GET_LIST_CONTRACT_TIMELINE_FAIL = 'GET_LIST_CONTRACT_TIMELINE_FAIL';

