export const GET_LIST_CONTACT = 'GET_LIST_CONTACT';
export const GET_LIST_CONTACT_SUCCESS = 'GET_LIST_CONTACT_SUCCESS';
export const GET_LIST_CONTACT_FAIL = 'GET_LIST_CONTACT_FAIL';

export const SET_KEYWORD_SEARCH = 'SET_KEYWORD_SEARCH';
export const SET_DEPARTMENT_SELECTED = 'SET_DEPARTMENT_SELECTED';
export const SET_BRANCH_SELECTED = 'SET_BRANCH_SELECTED';
