export const GET_LIST_CUSTOMER = 'GET_LIST_CUSTOMER';
export const GET_LIST_CUSTOMER_SUCCESS = 'GET_LIST_CUSTOMER_SUCCESS';
export const GET_LIST_CUSTOMER_FAIL = 'GET_LIST_CUSTOMER_FAIL';

export const GET_LIST_SELLER = 'GET_LIST_SELLER';
export const GET_LIST_SELLER_SUCCESS = 'GET_LIST_SELLER_SUCCESS';
export const GET_LIST_SELLER_FAIL = 'GET_LIST_SELLER_FAIL';
