export const GET_LIST_LOCATION_CUSTOMER = 'GET_LIST_LOCATION_CUSTOMER';
export const GET_LIST_LOCATION_CUSTOMER_SUCCESS = 'GET_LIST_LOCATION_CUSTOMER_SUCCESS';
export const GET_LIST_LOCATION_CUSTOMER_FAIL = 'GET_LIST_LOCATION_CUSTOMER_FAIL';
