export const GET_SUMMARY_PROGRESS = 'GET_SUMMARY_PROGRESS';
export const GET_SUMMARY_PROGRESS_SUCCESS = 'GET_SUMMARY_PROGRESS_SUCCESS';
export const GET_SUMMARY_PROGRESS_FAIL = 'GET_SUMMARY_PROGRESS_FAIL';

export const GET_NPV = 'GET_NPV';
export const GET_NPV_SUCCESS = 'GET_NPV_SUCCESS';
export const GET_NPV_FAIL = 'GET_NPV_FAIL';

export const GET_RECOVERY = 'GET_RECOVERY';
export const GET_RECOVERY_SUCCESS = 'GET_RECOVERY_SUCCESS';
export const GET_RECOVERY_FAIL = 'GET_RECOVERY_FAIL';

export const GET_DELINQUENT = 'GET_DELINQUENT';
export const GET_DELINQUENT_SUCCESS = 'GET_DELINQUENT_SUCCESS';
export const GET_DELINQUENT_FAIL = 'GET_DELINQUENT_FAIL';

export const GET_INSURANCE_INFORMED = 'GET_INSURANCE_INFORMED';
export const GET_INSURANCE_INFORMED_SUCCESS = 'GET_INSURANCE_INFORMED_SUCCESS';
export const GET_INSURANCE_INFORMED_FAIL = 'GET_INSURANCE_INFORMED_FAIL';

export const SET_FROM_DATE = 'SET_FROM_DATE';
export const SET_TO_DATE = 'SET_TO_DATE';
export const SET_SUB_TEAM_SELECTED = 'SET_SUB_TEAM_SELECTED';
export const SET_TEAM_MEMBER_SELECTED = 'SET_TEAM_MEMBER_SELECTED';
export const SET_ID_MODAL_DATE = 'SET_ID_MODAL_DATE';
export const SET_ID_CHIP_DATE = 'SET_ID_CHIP_DATE';
export const SET_VIEW_BY_TEAM = 'SET_VIEW_BY_TEAM';
export const CLEAR_FILTER = 'CLEAR_FILTER';
