export const GET_LIST_E_COIN_REPORT = 'GET_LIST_E_COIN_REPORT';
export const GET_LIST_E_COIN_REPORT_SUCCESS = 'GET_LIST_E_COIN_REPORT_SUCCESS';
export const GET_LIST_E_COIN_REPORT_FAIL = 'GET_LIST_E_COIN_REPORT_FAIL';

export const GET_LIST_ORDER_HISTORY = 'GET_LIST_ORDER_HISTORY';
export const GET_LIST_ORDER_HISTORY_SUCCESS = 'GET_LIST_ORDER_HISTORY_SUCCESS';
export const GET_LIST_ORDER_HISTORY_FAIL = 'GET_LIST_ORDER_HISTORY_FAIL';

export const GET_E_COIN_TOTAL = 'GET_E_COIN_TOTAL';
export const GET_E_COIN_TOTAL_SUCCESS = 'GET_E_COIN_TOTAL_SUCCESS';
export const GET_E_COIN_TOTAL_FAIL = 'GET_E_COIN_TOTAL_FAIL';
