export const GET_LIST_REQUEST_E_FLOW = 'GET_LIST_REQUEST_E_FLOW';
export const GET_LIST_REQUEST_E_FLOW_SUCCESS = 'GET_LIST_REQUEST_E_FLOW_SUCCESS';
export const GET_LIST_REQUEST_E_FLOW_FAIL = 'GET_LIST_REQUEST_E_FLOW_FAIL';

export const SET_KIND_SELECTED_E_FLOW = 'SET_KIND_SELECTED_E_FLOW';
export const SET_REQUEST_ID_E_FLOW = 'SET_REQUEST_ID_E_FLOW';
export const SET_PROPOSED_BY_E_FLOW = 'SET_PROPOSED_BY_E_FLOW';
export const SET_LESSEE_NAME_E_FLOW = 'SET_LESSEE_NAME_E_FLOW';
export const SET_DESCRIPTION_E_FLOW = 'SET_DESCRIPTION_E_FLOW';
export const SET_STATUS_SELECTED_E_FLOW = 'SET_STATUS_SELECTED_E_FLOW';

export const GET_LIST_APPROVER_E_FLOW = 'GET_LIST_APPROVER_E_FLOW';
export const GET_LIST_APPROVER_E_FLOW_SUCCESS = 'GET_LIST_APPROVER_E_FLOW_SUCCESS';
export const GET_LIST_APPROVER_E_FLOW_FAIL = 'GET_LIST_APPROVER_E_FLOW_FAIL';

