export const GET_LIST_REQUEST_E_REVIEW = 'GET_LIST_REQUEST_E_REVIEW';
export const GET_LIST_REQUEST_E_REVIEW_SUCCESS = 'GET_LIST_REQUEST_E_REVIEW_SUCCESS';
export const GET_LIST_REQUEST_E_REVIEW_FAIL = 'GET_LIST_REQUEST_E_REVIEW_FAIL';

export const SET_KIND_SELECTED_E_REVIEW = 'SET_KIND_SELECTED_E_REVIEW';
export const SET_REQUEST_ID_E_REVIEW = 'SET_REQUEST_ID_E_REVIEW';
export const SET_PROPOSED_BY_E_REVIEW = 'SET_PROPOSED_BY_E_REVIEW';
export const SET_LESSEE_NAME_E_REVIEW = 'SET_LESSEE_NAME_E_REVIEW';
export const SET_DESCRIPTION_E_REVIEW = 'SET_DESCRIPTION_E_REVIEW';
export const SET_STATUS_SELECTED_E_REVIEW = 'SET_STATUS_SELECTED_E_REVIEW';

export const GET_LIST_COMMENT_E_REVIEW = 'GET_LIST_COMMENT_E_REVIEW';
export const GET_LIST_COMMENT_E_REVIEW_SUCCESS = 'GET_LIST_COMMENT_E_REVIEW_SUCCESS';
export const GET_LIST_COMMENT_E_REVIEW_FAIL = 'GET_LIST_COMMENT_E_REVIEW_FAIL';
