export const GET_LIST_FIXED_ASSET = 'GET_LIST_FIXED_ASSET';
export const GET_LIST_FIXED_ASSET_SUCCESS = 'GET_LIST_FIXED_ASSET_SUCCESS';
export const GET_LIST_FIXED_ASSET_FAIL = 'GET_LIST_FIXED_ASSET_FAIL';

export const ADD_LIST_ASSET_SCAN = 'ADD_LIST_ASSET_SCAN';
export const CLEAR_LIST_ASSET_SCAN = 'CLEAR_LIST_ASSET_SCAN';
