export const GET_LIST_GENERAL_RFA = 'GET_LIST_GENERAL_RFA';
export const GET_LIST_GENERAL_RFA_SUCCESS = 'GET_LIST_GENERAL_RFA_SUCCESS';
export const GET_LIST_GENERAL_RFA_FAIL = 'GET_LIST_GENERAL_RFA_FAIL';
