export const GET_LIST_INSURANCE_CONTRACT = 'GET_LIST_INSURANCE_CONTRACT';
export const GET_LIST_INSURANCE_CONTRACT_SUCCESS =
	'GET_LIST_INSURANCE_CONTRACT_SUCCESS';
export const GET_LIST_INSURANCE_CONTRACT_FAIL = 'GET_LIST_INSURANCE_CONTRACT_FAIL';
