export const GET_LIST_LEAVE_REQUEST = 'GET_LIST_LEAVE_REQUEST';
export const GET_LIST_LEAVE_REQUEST_SUCCESS = 'GET_LIST_LEAVE_REQUEST_SUCCESS';
export const GET_LIST_LEAVE_REQUEST_FAIL = 'GET_LIST_LEAVE_REQUEST_FAIL';

export const GET_LIST_DAY_OFF_REMAINING = 'GET_LIST_DAY_OFF_REMAINING';
export const GET_LIST_DAY_OFF_REMAINING_SUCCESS = 'GET_LIST_DAY_OFF_REMAINING_SUCCESS';
export const GET_LIST_DAY_OFF_REMAINING_FAIL = 'GET_LIST_DAY_OFF_REMAINING_FAIL';
