export const GET_LIST_MESSAGE = 'GET_LIST_MESSAGE';
export const GET_LIST_MESSAGE_SUCCESS = 'GET_LIST_MESSAGE_SUCCESS';
export const GET_LIST_MESSAGE_FAIL = 'GET_LIST_MESSAGE_FAIL';

export const SET_NEW_MESSAGE = 'SET_NEW_MESSAGE';
export const SET_USER_TYPING = 'SET_LIST_USER_TYPING';
export const CLEAR_USER_TYPING = 'CLEAR_LIST_USER_TYPING';
