export const SET_LIST_NOTIFICATION = 'SET_LIST_NOTIFICATION';
export const SET_NUMBER_UNREAD_NOTIFICATION = 'SET_NUMBER_UNREAD_NOTIFICATION';
export const SET_LIST_PROMOTION = 'SET_LIST_PROMOTION';
export const SET_NUMBER_UNREAD_PROMOTION = 'SET_NUMBER_UNREAD_PROMOTION';
export const GET_NUMBER_UNREAD_FAIL = 'GET_NUMBER_UNREAD_FAIL';
export const GET_NUMBER_UNREAD_SUCCESS = 'GET_NUMBER_UNREAD_SUCCESS';

