export const GET_LIST_QUOTATION = 'GET_LIST_QUOTATION';
export const GET_LIST_QUOTATION_SUCCESS = 'GET_LIST_QUOTATION_SUCCESS';
export const GET_LIST_QUOTATION_FAIL = 'GET_LIST_QUOTATION_FAIL';

export const GET_QUOTATION_DETAIL = 'GET_QUOTATION_DETAIL';
export const GET_QUOTATION_DETAIL_SUCCESS = 'GET_QUOTATION_DETAIL_SUCCESS';
export const GET_QUOTATION_DETAIL_FAIL = 'GET_QUOTATION_DETAIL_FAIL';

export const GET_LIST_TENOR = 'GET_LIST_TENOR';
export const GET_LIST_TENOR_SUCCESS = 'GET_LIST_TENOR_SUCCESS';
export const GET_LIST_TENOR_FAIL = 'GET_LIST_TENOR_FAIL';

export const SET_LIST_TENOR = 'SET_LIST_TENOR';

export const CALCULATION_QUOTATION = 'CALCULATION_QUOTATION';
export const CALCULATION_QUOTATION_SUCCESS = 'CALCULATION_QUOTATION_SUCCESS';
export const CALCULATION_QUOTATION_FAIL = 'CALCULATION_QUOTATION_FAIL';

export const RESET_QUOTATION_RESULT = 'RESET_QUOTATION_RESULT';
