export const GET_ASSET_CHECKING_REQUESTS = "GET_ASSET_CHECKING_REQUESTS";
export const GET_ASSET_CHECKING_REQUESTS_SUCCESS =
    "GET_ASSET_CHECKING_REQUESTS_SUCCESS";
export const GET_ASSET_CHECKING_REQUESTS_FAIL = "GET_ASSET_CHECKING_REQUESTS_FAIL";
