export const GET_LIST_ROOM_MEMBER_RC = "GET_LIST_ROOM_MEMBER_RC";
export const GET_LIST_ROOM_MEMBER_RC_SUCCESS =
  "GET_LIST_ROOM_MEMBER_RC_SUCCESS";
export const GET_LIST_ROOM_MEMBER_RC_FAIL = "GET_LIST_ROOM_MEMBER_RC_FAIL";

export const ADD_USER_INVITED_RC = "ADD_USER_INVITED_RC";
export const REMOVE_USER_INVITED_RC = "REMOVE_USER_INVITED_RC";
export const REMOVE_All_USER_INVITED_RC = "REMOVE_All_USER_INVITED_RC";

export const GET_LIST_ROOM_RC = "GET_LIST_ROOM_RC";
export const GET_LIST_ROOM_RC_SUCCESS = "GET_LIST_ROOM_RC_SUCCESS";
export const GET_LIST_ROOM_RC_FAIL = "GET_LIST_ROOM_RC_FAIL";

export const SET_ROOM_CHANGE = "SET_READ_MESSAGE";
export const SET_NUMBER_MESSAGE_UNREAD = "SET_NUMBER_MESSAGE_UNREAD";

export const GET_LIST_REQUEST = 'GET_LIST_REQUEST';
export const GET_LIST_REQUEST_SUCCESS = 'GET_LIST_REQUEST_SUCCESS';
export const GET_LIST_REQUEST_FAIL = 'GET_LIST_REQUEST_FAIL';
